### ISSUE TITLE
Providers, new `health check`,`kill` and `shut down` smart contacts.

### ISSUE THREAD

**Issue by Sriep** [0chain/system_test#324] opened 2022-07-06 10:31 UTC
https://github.com/0chain/0chain/issues/1040, https://github.com/0chain/0chain/issues/1044, https://github.com/0chain/0chain/issues/1045, https://github.com/0chain/0chain/issues/1046

Need system tests for three new endpoints for each of the five providers, miners, sharders, blobbers, validators and authorises. So fifteen endpoints altogether.

1. `health check` If a provider does not send a health check regularly enough it gets temporarily deactivated.
2. `shut down` a provider can permanently disable itself. It does not take on existing commitments but must horners its existing commitments. 
3. `kill` the 0chain owner can permanently shut down a provider. It receives no more rewards but is otherwise like `shut down.

Following implement this for miners, sharders blobbers and validators. Authorisers to come.
* https://github.com/0chain/0chain/pull/1454
* https://github.com/0chain/0chain/pull/1439

**Comment by Kishan-Dhakan** [comment] 2023-03-22 19:50
Dupe of https://github.com/0chain/system_test/issues/570

**Closed by Kishan-Dhakan** 2023-03-22 19:50 UTC
Labels: mainnet
