### ISSUE TITLE
Update system test for file downloads

### ISSUE THREAD

**Issue by lpoli** [0chain/system_test#176] opened 2022-01-30 04:06 UTC
https://github.com/0chain/blobber/pull/509

Above PR is failing in system tests. I've corrected unit tests for the changes I've made.
The change that affected system test is;
1. All clients other than allocation owner must provide `authticket` to download shared file.
2. Error message. Some error response seemed too repetitive print, some were seemingly not explanatory.
3. Order of error response. Some error checking is done earlier because it would not make sense to check them at the bottom of function simply to discard whole file retrieval process.

**Comment by stewartie4** [comment] 2022-01-30 13:16
Hey @lpoli if code you have changed is causing system tests to fail you'll need to investigate why and open a system_tests PR with the fixes
The reason being we don't have the context to tell the difference between expected and genuine errors on your PR
There are also multiple PRs requiring test updates merging at any time and we don't have time to update them all
Thanks

**Comment by Kishan-Dhakan** [comment] 2022-02-22 08:08
Closing this as original PR mentioned in the issue is closed too. Auth-ticket test changes were merged too, recently. Please re-open if needed.

**Closed by Kishan-Dhakan** 2022-02-22 08:08 UTC
